package ru.alafonin4.Entity;

public enum Stage {
    EnterFirstName,
    EnterNameOfItemToDelete,
    EnterRussTextAbout,
    EnterTajikTextAbout,
    EnterQuestionToAdd,
    EnterDifficultyOfQuestion,
    EnterRightAnswerToAdd,
    EnterFalseAnswerToAdd,
    EnterImageOrder,
    EnterNewAdminUser,
    EnterListOfQuestions,
    EnterListOfWords,
    ChangeRussTextAbout,
    ChangeTajikTextAbout,
    ChangeTextSupport,
    ChangePhotoSupport,
    ChangePhotoAbout,
    EnterRussTextSupport,
    EnterTajikTextSupport,
    ChangeRussTextSupport,
    ChangeTajikTextSupport,
    ChangingStatInItem,
    DoingNothing,
    EnterCostOfItem,
    ChangingList,
    EnterToAddToRes,
    EnterToSubToRes,
    EnterUrlOfItemToAdd,
    EnterCountOfStarsFromReview,
}

