version: '3.8'

services:
  huseynbot:
    build: .
    depends_on:
      - db_huseyn
    environment:
      - DB_URL=jdbc:postgresql://huseynbot:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=tgbot

  db_huseyn:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tgbot
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
